# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# XDC: imports/zynqbasic/zybo.xdc

# Block Designs: bd/Zynq_PS/Zynq_PS.bd
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==Zynq_PS || ORIG_REF_NAME==Zynq_PS} -quiet] -quiet

# IP: bd/Zynq_PS/ip/Zynq_PS_processing_system7_0_0/Zynq_PS_processing_system7_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==Zynq_PS_processing_system7_0_0 || ORIG_REF_NAME==Zynq_PS_processing_system7_0_0} -quiet] -quiet

# IP: bd/Zynq_PS/ip/Zynq_PS_axi_gpio_0_0/Zynq_PS_axi_gpio_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==Zynq_PS_axi_gpio_0_0 || ORIG_REF_NAME==Zynq_PS_axi_gpio_0_0} -quiet] -quiet

# IP: bd/Zynq_PS/ip/Zynq_PS_ps7_0_axi_periph_0/Zynq_PS_ps7_0_axi_periph_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==Zynq_PS_ps7_0_axi_periph_0 || ORIG_REF_NAME==Zynq_PS_ps7_0_axi_periph_0} -quiet] -quiet

# IP: bd/Zynq_PS/ip/Zynq_PS_rst_ps7_0_100M_0/Zynq_PS_rst_ps7_0_100M_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==Zynq_PS_rst_ps7_0_100M_0 || ORIG_REF_NAME==Zynq_PS_rst_ps7_0_100M_0} -quiet] -quiet

# IP: bd/Zynq_PS/ip/Zynq_PS_auto_pc_0/Zynq_PS_auto_pc_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==Zynq_PS_auto_pc_0 || ORIG_REF_NAME==Zynq_PS_auto_pc_0} -quiet] -quiet

# XDC: bd/Zynq_PS/ip/Zynq_PS_processing_system7_0_0/Zynq_PS_processing_system7_0_0.xdc
set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==Zynq_PS_processing_system7_0_0 || ORIG_REF_NAME==Zynq_PS_processing_system7_0_0} -quiet] {/inst } ]/inst ] -quiet] -quiet

# XDC: bd/Zynq_PS/ip/Zynq_PS_axi_gpio_0_0/Zynq_PS_axi_gpio_0_0_board.xdc
set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==Zynq_PS_axi_gpio_0_0 || ORIG_REF_NAME==Zynq_PS_axi_gpio_0_0} -quiet] {/U0 } ]/U0 ] -quiet] -quiet

# XDC: bd/Zynq_PS/ip/Zynq_PS_axi_gpio_0_0/Zynq_PS_axi_gpio_0_0_ooc.xdc

# XDC: bd/Zynq_PS/ip/Zynq_PS_axi_gpio_0_0/Zynq_PS_axi_gpio_0_0.xdc
#dup# set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==Zynq_PS_axi_gpio_0_0 || ORIG_REF_NAME==Zynq_PS_axi_gpio_0_0} -quiet] {/U0 } ]/U0 ] -quiet] -quiet

# XDC: bd/Zynq_PS/ip/Zynq_PS_rst_ps7_0_100M_0/Zynq_PS_rst_ps7_0_100M_0_board.xdc
set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==Zynq_PS_rst_ps7_0_100M_0 || ORIG_REF_NAME==Zynq_PS_rst_ps7_0_100M_0} -quiet] {/U0 } ]/U0 ] -quiet] -quiet

# XDC: bd/Zynq_PS/ip/Zynq_PS_rst_ps7_0_100M_0/Zynq_PS_rst_ps7_0_100M_0.xdc
#dup# set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==Zynq_PS_rst_ps7_0_100M_0 || ORIG_REF_NAME==Zynq_PS_rst_ps7_0_100M_0} -quiet] {/U0 } ]/U0 ] -quiet] -quiet

# XDC: bd/Zynq_PS/ip/Zynq_PS_rst_ps7_0_100M_0/Zynq_PS_rst_ps7_0_100M_0_ooc.xdc

# XDC: bd/Zynq_PS/ip/Zynq_PS_auto_pc_0/Zynq_PS_auto_pc_0_ooc.xdc

# XDC: bd/Zynq_PS/Zynq_PS_ooc.xdc
