# 
# Synthesis run script generated by Vivado
# 

set TIME_start [clock seconds] 
proc create_report { reportName command } {
  set status "."
  append status $reportName ".fail"
  if { [file exists $status] } {
    eval file delete [glob $status]
  }
  send_msg_id runtcl-4 info "Executing : $command"
  set retval [eval catch { $command } msg]
  if { $retval != 0 } {
    set fp [open $status w]
    close $fp
    send_msg_id runtcl-5 warning "$msg"
  }
}
set_param xicom.use_bs_reader 1
set_msg_config -id {Common 17-41} -limit 10000000
set_msg_config -id {Synth 8-256} -limit 10000
set_msg_config -id {Synth 8-638} -limit 10000
create_project -in_memory -part xc7z020clg400-1

set_param project.singleFileAddWarning.threshold 0
set_param project.compositeFile.enableAutoGeneration 0
set_param synth.vivado.isSynthRun true
set_msg_config -source 4 -id {IP_Flow 19-2162} -severity warning -new_severity info
set_property webtalk.parent_dir C:/Users/long-/Git/zyncbasic/zyncbasic.cache/wt [current_project]
set_property parent.project_path C:/Users/long-/Git/zyncbasic/zyncbasic.xpr [current_project]
set_property XPM_LIBRARIES {XPM_CDC XPM_FIFO XPM_MEMORY} [current_project]
set_property default_lib xil_defaultlib [current_project]
set_property target_language Verilog [current_project]
set_property board_part digilentinc.com:zybo-z7-20:part0:1.0 [current_project]
set_property ip_output_repo c:/Users/long-/Git/zyncbasic/zyncbasic.cache/ip [current_project]
set_property ip_cache_permissions {read write} [current_project]
read_verilog -library xil_defaultlib -sv {
  C:/Users/long-/Git/zyncbasic/zyncbasic.srcs/sources_1/imports/zynqbasic/hex2oled.sv
  C:/Users/long-/Git/zyncbasic/zyncbasic.srcs/sources_1/imports/zynqbasic/uart_tx.sv
  C:/Users/long-/Git/zyncbasic/zyncbasic.srcs/sources_1/imports/zynqbasic/zybo_top.sv
}
add_files C:/Users/long-/Git/zyncbasic/zyncbasic.srcs/sources_1/bd/Zynq_PS/Zynq_PS.bd
set_property used_in_implementation false [get_files -all c:/Users/long-/Git/zyncbasic/zyncbasic.srcs/sources_1/bd/Zynq_PS/ip/Zynq_PS_processing_system7_0_0/Zynq_PS_processing_system7_0_0.xdc]
set_property used_in_implementation false [get_files -all c:/Users/long-/Git/zyncbasic/zyncbasic.srcs/sources_1/bd/Zynq_PS/ip/Zynq_PS_axi_gpio_0_0/Zynq_PS_axi_gpio_0_0_board.xdc]
set_property used_in_implementation false [get_files -all c:/Users/long-/Git/zyncbasic/zyncbasic.srcs/sources_1/bd/Zynq_PS/ip/Zynq_PS_axi_gpio_0_0/Zynq_PS_axi_gpio_0_0_ooc.xdc]
set_property used_in_implementation false [get_files -all c:/Users/long-/Git/zyncbasic/zyncbasic.srcs/sources_1/bd/Zynq_PS/ip/Zynq_PS_axi_gpio_0_0/Zynq_PS_axi_gpio_0_0.xdc]
set_property used_in_implementation false [get_files -all c:/Users/long-/Git/zyncbasic/zyncbasic.srcs/sources_1/bd/Zynq_PS/ip/Zynq_PS_rst_ps7_0_100M_0/Zynq_PS_rst_ps7_0_100M_0_board.xdc]
set_property used_in_implementation false [get_files -all c:/Users/long-/Git/zyncbasic/zyncbasic.srcs/sources_1/bd/Zynq_PS/ip/Zynq_PS_rst_ps7_0_100M_0/Zynq_PS_rst_ps7_0_100M_0.xdc]
set_property used_in_implementation false [get_files -all c:/Users/long-/Git/zyncbasic/zyncbasic.srcs/sources_1/bd/Zynq_PS/ip/Zynq_PS_rst_ps7_0_100M_0/Zynq_PS_rst_ps7_0_100M_0_ooc.xdc]
set_property used_in_implementation false [get_files -all c:/Users/long-/Git/zyncbasic/zyncbasic.srcs/sources_1/bd/Zynq_PS/ip/Zynq_PS_auto_pc_0/Zynq_PS_auto_pc_0_ooc.xdc]
set_property used_in_implementation false [get_files -all C:/Users/long-/Git/zyncbasic/zyncbasic.srcs/sources_1/bd/Zynq_PS/Zynq_PS_ooc.xdc]

# Mark all dcp files as not used in implementation to prevent them from being
# stitched into the results of this synthesis run. Any black boxes in the
# design are intentionally left as such for best results. Dcp files will be
# stitched into the design at a later time, either when this synthesis run is
# opened, or when it is stitched into a dependent implementation run.
foreach dcp [get_files -quiet -all -filter file_type=="Design\ Checkpoint"] {
  set_property used_in_implementation false $dcp
}
read_xdc C:/Users/long-/Git/zyncbasic/zyncbasic.srcs/constrs_1/imports/zynqbasic/zybo.xdc
set_property used_in_implementation false [get_files C:/Users/long-/Git/zyncbasic/zyncbasic.srcs/constrs_1/imports/zynqbasic/zybo.xdc]

read_xdc dont_touch.xdc
set_property used_in_implementation false [get_files dont_touch.xdc]
set_param ips.enableIPCacheLiteLoad 0
close [open __synthesis_is_running__ w]

synth_design -top ZYBO_top -part xc7z020clg400-1


# disable binary constraint mode for synth run checkpoints
set_param constraints.enableBinaryConstraints false
write_checkpoint -force -noxdef ZYBO_top.dcp
create_report "synth_1_synth_report_utilization_0" "report_utilization -file ZYBO_top_utilization_synth.rpt -pb ZYBO_top_utilization_synth.pb"
file delete __synthesis_is_running__
close [open __synthesis_is_complete__ w]
